### ISSUE TITLE
Cleanup to-do list.

### ISSUE THREAD

**Issue by fedepedron** [MALBECC/lio#328]
This is for develop, so we do not die when compiling with analytics.
- [ ] Remove unused variables.
- [ ] Remove unused labels.
- [ ] Remove tabs wherever they are (if any).
- [ ] Move cublasmath, liosubsmath, and liomods all to f90.
- [ ] Change all real*8-like declarations to modern ones, or better yet, define our own real type.

**Comment by fedepedron** [comment]
Current orphan subs in develop:
* convert_types (maybe move to new *datatypes* module)
* dip (to a properties module)
* drive (maybe a lio "core" module?)
* fock commuts (to math module)
* get_restraint_energy_forces (eh... maybe on its own module)
* grid (also should have its own module, either that or core)
* init_lio (core)
* input_read (fileio)
* lio_finalize (core)
* liomain (core)
* packed_storage (utility? perhaps joining with errlog and liosubs)
* properties (properties module)
* read_ecp (either to fileio or ECP modules)
* dft_get_mm_forces and dft_get_qm_forces (this one is tricky, since it is called from amber).
* SCF_exter (also tricky, for the same reasons).
